[2024-09-26T15:04:12.936+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-26T15:04:12.953+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: find_activity.get_activity manual__2024-09-26T15:04:11.915792+00:00 [queued]>
[2024-09-26T15:04:12.964+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: find_activity.get_activity manual__2024-09-26T15:04:11.915792+00:00 [queued]>
[2024-09-26T15:04:12.964+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-26T15:04:12.984+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_activity> on 2024-09-26 15:04:11.915792+00:00
[2024-09-26T15:04:12.992+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=738) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-26T15:04:12.994+0000] {standard_task_runner.py:72} INFO - Started process 739 to run task
[2024-09-26T15:04:12.994+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'find_activity', 'get_activity', 'manual__2024-09-26T15:04:11.915792+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/find_activity.py', '--cfg-path', '/tmp/tmp87vc9b8k']
[2024-09-26T15:04:12.995+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask get_activity
[2024-09-26T15:04:13.044+0000] {task_command.py:467} INFO - Running <TaskInstance: find_activity.get_activity manual__2024-09-26T15:04:11.915792+00:00 [running]> on host 07583ab04db1
[2024-09-26T15:04:13.132+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='find_activity' AIRFLOW_CTX_TASK_ID='get_activity' AIRFLOW_CTX_EXECUTION_DATE='2024-09-26T15:04:11.915792+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-26T15:04:11.915792+00:00'
[2024-09-26T15:04:13.134+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-26T15:04:13.920+0000] {python.py:240} INFO - Done. Returned value was: {'activity': 'Bake a pie with some friends', 'availability': 0.3, 'type': 'cooking', 'participants': 3, 'price': 0.3, 'accessibility': 'Few to no challenges', 'duration': 'hours', 'kidFriendly': True, 'link': '', 'key': '3141592'}
[2024-09-26T15:04:13.947+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-26T15:04:13.948+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=find_activity, task_id=get_activity, run_id=manual__2024-09-26T15:04:11.915792+00:00, execution_date=20240926T150411, start_date=20240926T150412, end_date=20240926T150413
[2024-09-26T15:04:13.975+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-26T15:04:14.000+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-26T15:04:14.005+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
