[2024-10-07T14:28:35.341+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-07T14:28:35.365+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_data_new.success manual__2024-10-07T14:28:26.837646+00:00 [queued]>
[2024-10-07T14:28:35.383+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_data_new.success manual__2024-10-07T14:28:26.837646+00:00 [queued]>
[2024-10-07T14:28:35.386+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-07T14:28:35.416+0000] {taskinstance.py:2888} INFO - Executing <Task(_BashDecoratedOperator): success> on 2024-10-07 14:28:26.837646+00:00
[2024-10-07T14:28:35.425+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=171) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-07T14:28:35.427+0000] {standard_task_runner.py:72} INFO - Started process 173 to run task
[2024-10-07T14:28:35.427+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transform_data_new', 'success', 'manual__2024-10-07T14:28:26.837646+00:00', '--job-id', '224', '--raw', '--subdir', 'DAGS_FOLDER/transform_data_new.py', '--cfg-path', '/tmp/tmphc79cch1']
[2024-10-07T14:28:35.430+0000] {standard_task_runner.py:105} INFO - Job 224: Subtask success
[2024-10-07T14:28:35.520+0000] {task_command.py:467} INFO - Running <TaskInstance: transform_data_new.success manual__2024-10-07T14:28:26.837646+00:00 [running]> on host 62f1fdba7656
[2024-10-07T14:28:35.673+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_data_new' AIRFLOW_CTX_TASK_ID='success' AIRFLOW_CTX_EXECUTION_DATE='2024-10-07T14:28:26.837646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-07T14:28:26.837646+00:00'
[2024-10-07T14:28:35.675+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-07T14:28:35.721+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-07T14:28:35.723+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "The DAG is running well"']
[2024-10-07T14:28:35.740+0000] {subprocess.py:86} INFO - Output:
[2024-10-07T14:28:35.743+0000] {subprocess.py:93} INFO - The DAG is running well
[2024-10-07T14:28:35.744+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-07T14:28:35.785+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-07T14:28:35.787+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=transform_data_new, task_id=success, run_id=manual__2024-10-07T14:28:26.837646+00:00, execution_date=20241007T142826, start_date=20241007T142835, end_date=20241007T142835
[2024-10-07T14:28:35.845+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-07T14:28:35.879+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-07T14:28:35.887+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
