[2024-10-01T12:20:57.271+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-01T12:20:57.288+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_data.success manual__2024-10-01T12:20:53.654213+00:00 [queued]>
[2024-10-01T12:20:57.298+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_data.success manual__2024-10-01T12:20:53.654213+00:00 [queued]>
[2024-10-01T12:20:57.299+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-01T12:20:57.317+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): success> on 2024-10-01 12:20:53.654213+00:00
[2024-10-01T12:20:57.326+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=260) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-01T12:20:57.329+0000] {standard_task_runner.py:72} INFO - Started process 262 to run task
[2024-10-01T12:20:57.328+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transform_data', 'success', 'manual__2024-10-01T12:20:53.654213+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/transform_data.py', '--cfg-path', '/tmp/tmpt63ngusl']
[2024-10-01T12:20:57.331+0000] {standard_task_runner.py:105} INFO - Job 184: Subtask success
[2024-10-01T12:20:57.385+0000] {task_command.py:467} INFO - Running <TaskInstance: transform_data.success manual__2024-10-01T12:20:53.654213+00:00 [running]> on host 9ff0d37a02a4
[2024-10-01T12:20:57.515+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_data' AIRFLOW_CTX_TASK_ID='success' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T12:20:53.654213+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T12:20:53.654213+00:00'
[2024-10-01T12:20:57.517+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-01T12:20:57.523+0000] {logging_mixin.py:190} INFO - This DAG is running well
[2024-10-01T12:20:57.524+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-01T12:20:57.535+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-01T12:20:57.539+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=transform_data, task_id=success, run_id=manual__2024-10-01T12:20:53.654213+00:00, execution_date=20241001T122053, start_date=20241001T122057, end_date=20241001T122057
[2024-10-01T12:20:57.586+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-01T12:20:57.605+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T12:20:57.609+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
